/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.AccesoDAO;
import javax.swing.JOptionPane;
import to.AccesoTO;

/**
 *
 * @author Joel
 */
public class RegistroEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form RegistroEmpleado
     */
    public RegistroEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtClave = new javax.swing.JPasswordField();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnRegresar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Clave");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, -1));

        jtxtClave.setEditable(false);
        jtxtClave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jtxtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, -1));

        jbtnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnRegistrar.setText("Registrar");
        jbtnRegistrar.setEnabled(false);
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 40));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setEnabled(false);
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, 40));

        jbtnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnNuevo.setText("Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 90, 40));

        jbtnRegresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnRegresar.setText("Regresar");
        jbtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 90, 40));

        jbtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setEnabled(false);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
        try {
            AccesoTO objAccesoTO = new AccesoTO();
            objAccesoTO.setUsuario(jtxtUsuario.getText().trim());
            objAccesoTO.setClave(jtxtClave.getText().trim());
            AccesoDAO objAccesoDAO = new AccesoDAO();
            objAccesoDAO.RegistrarEmpleado(objAccesoTO);
            JOptionPane.showMessageDialog(null, "Empleado Registrado");
            limpiarJTxt();
            jtxtUsuario.setEditable(false);
            jtxtClave.setEditable(false);
            jbtnCancelar.setEnabled(false);
            jbtnRegistrar.setEnabled(false);
            jbtnReset.setEnabled(false);
            jbtnNuevo.setEnabled(true);
            jbtnRegresar.setEnabled(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtnRegistrarActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        limpiarJTxt();
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        jtxtUsuario.setEditable(true);
        jtxtClave.setEditable(true);
        jbtnCancelar.setEnabled(true);
        jbtnRegistrar.setEnabled(true);
        jbtnReset.setEnabled(true);
        jbtnNuevo.setEnabled(false);
        jbtnRegresar.setEnabled(false);
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegresarActionPerformed
        Menú objMenú = new Menú();
        objMenú.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jbtnRegresarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        jtxtUsuario.setEditable(false);
        jtxtClave.setEditable(false);
        jbtnCancelar.setEnabled(false);
        jbtnRegistrar.setEnabled(false);
        jbtnReset.setEnabled(false);
        jbtnNuevo.setEnabled(true);
        jbtnRegresar.setEnabled(true);
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEmpleado().setVisible(true);
            }
        });
    }

    private void limpiarJTxt() {
        jtxtClave.setText("");
        jtxtUsuario.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnRegistrar;
    private javax.swing.JButton jbtnRegresar;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JPasswordField jtxtClave;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
